#application: soundingwell1
#version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /
  script: python/main.py
  
- url: /css
  static_dir: css
  
- url: /wavFiles
  script: python/main.py
  
- url: /resources
  static_dir: resources

  #login: required
  #auth_fail_action: unauthorized
  
#- url: /
#  script: main.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest  



